name: CD Deployment

on:
  workflow_run:
    workflows: ["CI"]
    branches: [main]
    types:
      - completed

permissions:
  contents: write # Needed for gh-pages deployment
  actions: read

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    if: >
      github.event.workflow_run.event == 'push' &&
      github.event.workflow_run.conclusion == 'success'
    steps:
      - name: Download artifact from CI
        uses: actions/download-artifact@v4
        with:
          name: production-build
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Debug downloaded files
        run: |
          echo "Current directory: $(pwd)"
          ls -R

      - name: Create gh-pages branch if missing
        run: |
          # Check if branch exists
          if ! git ls-remote --exit-code origin gh-pages; then
            git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git config --global user.name "GitHub Actions"
            git checkout --orphan gh-pages
            git rm -rf .
            touch .nojekyll
            git add .nojekyll
            git commit -m "Initialize gh-pages branch"
            git push origin gh-pages
          fi

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./production-build
          force_orphan: true
          keep_files: false
          enable_jekyll: false
          allow_empty_commit: false
