name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    branches: [main]
    types: [completed]

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Verify Correct CI Run
        uses: actions/github-script@v7
        id: ci-run-check
        with:
          script: |
            const ciRun = await github.rest.actions.getWorkflowRun({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: context.payload.workflow_run.id,
            });

            const isValid = ciRun.data.event === 'push' && ciRun.data.head_branch === 'main';

            core.setOutput('valid', isValid);
            return isValid;

      - name: Download Artifact from Push CI
        if: steps.ci-run-check.outputs.valid == 'true'
        uses: actions/download-artifact@v4
        with:
          name: production-build
          path: dist
          repository: ${{ github.repository }}
          run-id: ${{ github.event.workflow_run.id }}

      - name: Configure GitHub Pages
        if: steps.ci-run-check.outputs.valid == 'true'
        uses: actions/configure-pages@v4

      - name: Upload Pages Artifact
        if: steps.ci-run-check.outputs.valid == 'true'
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist/

      - name: Deploy to GitHub Pages
        if: steps.ci-run-check.outputs.valid == 'true'
        id: deployment
        uses: actions/deploy-pages@v4
