# The name of the workflow
name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  actions: write # Required for workflow-to-workflow artifact access
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build: # The unique identifier for the job
    name: Build # The name for the job, which is displayed in the GitHub UI
    runs-on: ${{ matrix.os }} # The type of machine to run the job on
    strategy: # Defines a matrix of different job configurations
      matrix:
        os: [ubuntu-latest]
        node_version: ["20.x"]
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Node.js and cache dependencies
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node_version }}
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"

      - name: Install dependencies here
        run: npm ci

      - name: Check code format with Prettier
        run: npm run format:fix

      - name: Check code for linting errors with ESLint
        run: npm run lint

      - name: Test with Vitest
        run: npm run test

      - name: Type check with TypeScript
        run: npm run typecheck

      - name: Build with Vite
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: production-build
          path: ./dist
          retention-days: 3
          if-no-files-found: error
